### PR TITLE
Added Toolbar Functions

### LINKED ISSUE #37: Make the buttons functional
- The buttons that you create make them functional, i.e. write the javascript functions to store and upload the codes etc.

### PR DESCRIPTION
**Pull request by HRC-123**
Issues Resolved : #37 
@ravinder-chadha Hello sir,

I have added functions for all the buttons in the toolbar.

> Video on how they work

https://github.com/iRootsOrg/CodeBase/assets/106550364/a2022f0c-411a-4b8f-a795-4303e52078af

Please inform me if any changes need to be made.
Thank you.

### CODE REVIEW

**Comment by ravinder-chadha** [comment]
Hi @HRC-123 ,
Can you please work on
- remove the choose language option when clicked on folder
- use the save button to save the present state of codes in the browser to local storage of browser itself. That if the person refreshes the state must remain same.

**Comment by HRC-123** [comment]
> Hi @HRC-123 , Can you please work on
> 
> * remove the choose language option when clicked on folder
> * use the save button to save the present state of codes in the browser to local storage of browser itself. That if the person refreshes the state must remain same.

Sorry sir, I didn't get the first point
Do you mean the language option should not appear until a file is clicked right?

**Comment by ravinder-chadha** [comment]
Right

**Comment by HRC-123** [comment]
@ravinder-chadha Hello sir,
I have worked on the issues
**Rectified Issues:**
- Language dropdown shows only when file is clicked
- The folder,files store locally
- Boiler plate code applies if there are no initial changes in code

image

image


Please inform me if any further changes need to be made.
Thank you.

**Review by ravinder-chadha — APPROVED** [review]

**Pull request merged**
