### PR TITLE
NewComp-branch

### PR DESCRIPTION
**Pull request by PiyushSinghcodes**
a check needed

### CODE REVIEW

**Comment by ravinder-chadha** [comment]
Please add screenshots

**Comment by PiyushSinghcodes** [comment]
**Sir please check if it is correct as it is will be linked so a check needed:::**

**INPUT :::**
{
  "language": "java",
  "code": "public class Main {\n    public static void main(String[] args) {\n        java.util.Scanner scanner = new java.util.Scanner(System.in);\n        String name = scanner.nextLine();\n        String gender = scanner.nextLine();\n        int age = scanner.nextInt();\n        long mobile_no = scanner.nextLong();\n        double cgpa = scanner.nextDouble();\n        System.out.println(\"Name: \" + name);\n        System.out.println(\"Gender: \" + gender);\n        System.out.println(\"Age: \" + age);\n        System.out.println(\"Mobile Number: \" + mobile_no);\n        System.out.println(\"CGPA: \" + cgpa);\n        scanner.close();\n    }\n}",
  "inputs": ["Alice", "F", "25", "1234567890", "3.75"]
}

**OUTPUT**

{
  "statusCode": 200,
  "body": {
    "statusCode": 200,
    "body": "Name: Alice\nGender: F\nAge: 25\nMobile Number: 1234567890\nCGPA: 3.75"
  }
}

Screenshot 2024-07-10 at 1 13 33 PM

**Comment by PiyushSinghcodes** [comment]
**Here are python and C++ compiles as well::**
Screenshot 2024-07-10 at 1 23 40 PM

Screenshot 2024-07-10 at 1 22 57 PM

**Comment by PiyushSinghcodes** [comment]
There are 2 status showing in Java one because I was still working on the code in-order to get different status.Like code compiled then status is 200 but code throws an status 500 at exception case and 400 similarly.
I could do that in Java as I am used to it but with python and C++ I might need guidance.

**Comment by ravinder-chadha** [comment]
You can find how to use APIs in python and C++ so, you will get status codes in output for these APIs.
In python, You can also use `sys` for example:

```python
import sys

def main():
    try:
        # Your code here
        print("Code executed successfully!")
        sys.exit(0)  # Status code 0 indicates success
    except Exception as e:
        print(f"An error occurred: {e}")
        sys.exit(1)  # Status code 1 indicates an error

if __name__ == "__main__":
    main()
```

**Pull request merged**
