### PR TITLE
fixes issue #28

### LINKED ISSUE #28: Update the schema to have input and outputs linked to the code file
- Make sure the files have unique ids for the authors they are created by
- Make sure the files have only there own multiple test cases
- With multiple inputs which can be files also linked to there respective outputs which can be files (graphs) as well.

### PR DESCRIPTION
**Pull request by 17himanshu**
closes #28

### CODE REVIEW

**Comment by 17himanshu** [comment]
Sirt I have created inputOutputSchema which can be file or direct and then created testCaseSchema which has input and output and both these inputs and outputs are array of inputOutput Schema and then I have added testCases as array of the testCaseSchema and also added authorId which references itself to user table and have an unique value

**Review by ravinder-chadha — COMMENTED** [review]
Looks fine to me, Can you please resolve the merge conflicts. So that I can go ahead and merge.

**Comment by 17himanshu** [comment]
Sure I will do that right away

**Comment by 17himanshu** [comment]
I have resolve d the conflicts sir

**Review by ravinder-chadha — APPROVED** [review]

**Pull request merged**
